version: '3.8'


services:
  web:
    build: ./app
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/lib/letsencrypt:/var/lib/letsencrypt
        - /var/www/html:/var/www/html
      depends_on:
        - nginx
      command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email -d bonds2022.com  -d canberra2022.com
