version: '3.8'


services:
  web:
    build: ./app
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - web
    networks:
      nginx_net:
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./data/certbot/conf:/etc/letsencrypt
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    networks:
      nginx_net:
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./data/certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  nginx_net:
    name: nginx_net