version: '3.8'


services:
  web:
    build: ./app
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./www:/var/www
      - ./nginx-conf:/etc/nginx/conf.d