version: '3.8'


services:
  web:
    build: ./app
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./www:/var/www
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./www:/var/www
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email kda4001@gmail.com --agree-tos --no-eff-email --staging -d bonds2022.com  -d canberra2022.com